### ISSUE TITLE
Missing overrides.js

### ISSUE THREAD

**Issue by jeroenvermeulen** [mallocator/Munin-JQuery-Template#4]
Hi Ravi,
Thanks for the work you put in these jQuery templates for Munin.
I am missing the file `overrides.js`, if it contains user configuration, could you add an example?
The file is referenced here:
https://github.com/mallocator/Munin-JQuery-Template/blob/HEAD/templates/assets/js/overview.js#L375

**Comment by mallocator** [comment]
I added some info to the readme. I actually had to look it up in one of our old instances, because I haven't worked on this for so long. Turns out that this is just a link to the Munin overrides configuration. I don't know if that still exists in Munin 2, if not you can probably just delete that segment of the code. 

In any case, glad that you can still get this template running and that there are still people out there using it :)

**Comment by jeroenvermeulen** [comment]
I don't have any `munin-overrides.js` file on my server. 
We are running Munin 2.0.25-1ppa2~trusty.

I also can't find an example of this file online.
Maybe it was something only existing on your servers?

**Comment by mallocator** [comment]
You know, now that you mention it, you're right. We used that file to generate the munin configuration for all our servers. So in yeah, delete/ignore that part of the code :)
